apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks5-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks5-proxy
  template:
    metadata:
      labels:
        app: socks5-proxy
    spec:
      containers:
        - name: proxy
          image: serjs/go-socks5-proxy:latest
          ports:
          - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: socks5-proxy
spec:
  selector:
    app: socks5-proxy
  ports:
  - port: 1080
    targetPort: 1080
  type: ClusterIP