name: FileMaker Provider Tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit SHA'
        required: false
        default: ''
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit SHA'
        required: false
        type: string
    outputs:
      success:
        description: "Whether the tests were successful"
        value: ${{ jobs.test.outputs.success }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set_output.outputs.success }}
    container:
      image: ghcr.io/arktci/airflow-providers/filemaker-dependencies:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Run tests
        run: |
          cd filemaker
          python -m pytest --cov=src tests/ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./filemaker/coverage.xml
          fail_ci_if_error: false
          
      - name: Set output
        id: set_output
        run: echo "success=true" >> $GITHUB_OUTPUT