name: FileMaker Provider Linting

on:
  push:
    branches:
      - dev
    paths:
      - "filemaker/**"
  pull_request:
    paths:
      - "filemaker/**"
  workflow_dispatch:

jobs:
  check-if-bot-commit:
    runs-on: ubuntu-latest
    outputs:
      is_bot: ${{ steps.check_bot_commit.outputs.is_bot }}
    steps:
      - name: Check if commit is from GitHub Actions
        id: check_bot_commit
        run: |
          if [[ "${{ github.event.head_commit.author.name }}" == "GitHub Actions" ]]; then
            echo "is_bot=true" >> $GITHUB_OUTPUT
          else
            echo "is_bot=false" >> $GITHUB_OUTPUT
          fi

  lint:
    needs: check-if-bot-commit
    if: needs.check-if-bot-commit.outputs.is_bot != 'true'
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd filemaker
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run flake8
        run: |
          cd filemaker
          flake8 src tests

      - name: Run black
        run: |
          cd filemaker
          black --check src tests

      - name: Run isort
        run: |
          cd filemaker
          isort --check src tests

      - name: Run mypy
        run: |
          cd filemaker
          mypy src

      - name: Trigger test workflow if successful
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-filemaker-tests
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'