name: FileMaker Provider Version Bump (Standalone)

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      ref:
        description: 'Branch or commit SHA'
        required: false
        default: ''
  workflow_call:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: string
        default: 'patch'
      ref:
        description: 'Branch or commit SHA'
        required: false
        type: string
    outputs:
      new_version:
        description: "The new version after bumping"
        value: ${{ jobs.bump-version.outputs.new_version }}
      branch_name:
        description: "The branch name created for the release"
        value: ${{ jobs.bump-version.outputs.branch_name }}

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arktci/airflow-providers/filemaker-dependencies:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      branch_name: ${{ steps.create_branch.outputs.branch_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref || github.ref }}

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Create version file in filemaker folder
      - name: Get current version
        run: |
          cd filemaker
          # Extract version from existing file
          VERSION=$(grep -o '"[0-9]\+\.[0-9]\+\.[0-9]\+"' version.py | tr -d '"')
          echo "VERSION=$VERSION" > version.txt

      - name: Run version bump script
        id: bump
        run: |
          cd filemaker
          # No need to install bump2version as it's already in the container
          bump2version ${{ inputs.bump_type || github.event.inputs.bump_type || 'patch' }}
          
          # Read the new version
          NEW_VERSION=$(grep -o '"[0-9]\+\.[0-9]\+\.[0-9]\+"' version.py | tr -d '"')
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          
          # Update version.txt
          echo "VERSION=${NEW_VERSION}" > version.txt
          
          # Commit the changes
          git add version.txt version.py provider.yaml setup.py
          git commit -m "Bump version to ${NEW_VERSION}"

      - name: Create release branch
        id: create_branch
        run: |
          NEW_VERSION="${{ steps.bump.outputs.new_version }}"
          BRANCH_NAME="release/v${NEW_VERSION}"
          git checkout -b ${BRANCH_NAME}
          git push origin ${BRANCH_NAME}
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

  summary:
    name: Summary
    needs: [bump-version]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Display Results
        run: |
          echo "Version Bump Status: ${{ needs.bump-version.result }}"
          
          if [[ "${{ needs.bump-version.result }}" == "success" ]]; then
            echo "✅ Version bumped to ${{ needs.bump-version.outputs.new_version }}"
            echo "✅ Created branch ${{ needs.bump-version.outputs.branch_name }}"
            
            if [[ "${{ github.event_name }}" == "workflow_call" ]]; then
              echo "ℹ️ PR creation will be handled by the calling workflow"
            else
              echo "ℹ️ Run the create-pr workflow manually if needed"
            fi
          else
            echo "❌ Version bump failed"
          fi