name: FileMaker Provider Linting

on:
  repository_dispatch:
    types: [run-filemaker-lint]
  pull_request:
    paths:
      - "filemaker/src/**"
      - "filemaker/tests/**"
      - "!filemaker/requirements.txt"
      - "!filemaker/requirements-dev.txt"
  workflow_dispatch:

jobs:
  check-if-bot-commit:
    runs-on: ubuntu-latest
    outputs:
      is_bot: ${{ steps.check_bot_commit.outputs.is_bot }}
    steps:
      - name: Check if commit is from GitHub Actions
        id: check_bot_commit
        run: |
          # Default is not a bot
          IS_BOT="false"
          
          # Only check head_commit for push events
          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ github.event.head_commit.author.name }}" == "GitHub Actions" ]]; then
              IS_BOT="true"
            fi
          fi
          
          echo "is_bot=${IS_BOT}" >> $GITHUB_OUTPUT

  lint:
    needs: check-if-bot-commit
    if: needs.check-if-bot-commit.outputs.is_bot != 'true'
    name: Lint Code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/filemaker-dependencies:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}

      # No need to install dependencies as they're in the container

      - name: Run flake8
        run: |
          cd filemaker
          flake8 src tests

      - name: Run black
        run: |
          cd filemaker
          black --check src tests

      - name: Run isort
        run: |
          cd filemaker
          isort --check src tests

      - name: Run mypy
        run: |
          cd filemaker
          mypy src

      - name: Trigger test workflow if successful
        if: success() && (github.event_name == 'push' || github.event_name == 'repository_dispatch')
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-filemaker-tests
          client-payload: '{"ref": "${{ github.event.client_payload.ref || github.ref }}", "sha": "${{ github.event.client_payload.sha || github.sha }}"}'