name: FileMaker Provider Build Docker Image

on:
  repository_dispatch:
    types: [build-filemaker-docker-image]
  workflow_dispatch:
    inputs:
      provider_version:
        description: 'FileMaker provider version'
        required: true

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # Container not needed for this job as it's building a Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: extract_version
        run: |
          VERSION="${{ github.event.client_payload.provider_version || github.event.inputs.provider_version }}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./filemaker
          push: true
          tags: |
            yourdockerhub/filemaker-provider:latest
            yourdockerhub/filemaker-provider:${{ steps.extract_version.outputs.version }}
          build-args: |
            PROVIDER_VERSION=${{ steps.extract_version.outputs.version }}